-- Reorganización de carta: categoría Pedratas (antes 3 productos
-- sueltos dentro de "Especialidades", movidos a su categoría propia en el
-- script 2). Se añaden los modificadores que pidió el cliente: elegir
-- carne (ternera/pollo/mixto, ternera por defecto), salsas (mismo sistema
-- que kebab/dürüm/lahmacum) y extras (extra salsa, extra queso, pan de
-- kebab, todo +1€). Se añade además el tamaño nuevo "Pedrata XXL" a 12€.
-- Los precios de los 3 tamaños existentes no cambian (coinciden con lo que
-- confirmó el cliente: pequeña 4,50€, mediana 6€, grande 7€).
-- Seguro de re-ejecutar.

update menu_productos set precio = 4.5, modificadores = '[{"id":"carne","titulo":"Elige la carne","tipo":"unica","maxSeleccion":1,"opciones":[{"id":"ternera","nombre":"Ternera","precioExtra":0,"porDefecto":true},{"id":"pollo","nombre":"Pollo","precioExtra":0,"porDefecto":false},{"id":"mixto","nombre":"Mixto","precioExtra":0,"porDefecto":false}]},{"id":"salsas","titulo":"Salsas","tipo":"multiple","textoSiVacio":"Sin salsa","opciones":[{"id":"salsa-blanca","nombre":"Salsa de yogurt (Blanca)","ingrediente":"salsa blanca","precioExtra":0,"porDefecto":true},{"id":"salsa-roja","nombre":"Salsa de tomate (Roja)","ingrediente":"salsa roja","precioExtra":0,"porDefecto":true},{"id":"salsa-picante","nombre":"Salsa picante","ingrediente":"salsa picante","precioExtra":0,"porDefecto":false}]},{"id":"extras","titulo":"Extras","tipo":"multiple","opciones":[{"id":"extra-salsa","nombre":"Extra salsa","precioExtra":1,"porDefecto":false},{"id":"extra-queso","nombre":"Extra queso","precioExtra":1,"porDefecto":false},{"id":"pan-kebab","nombre":"Pan de kebab","precioExtra":1,"porDefecto":false}]}]'::jsonb where id = 'pedratas-pequena';
update menu_productos set precio = 6, modificadores = '[{"id":"carne","titulo":"Elige la carne","tipo":"unica","maxSeleccion":1,"opciones":[{"id":"ternera","nombre":"Ternera","precioExtra":0,"porDefecto":true},{"id":"pollo","nombre":"Pollo","precioExtra":0,"porDefecto":false},{"id":"mixto","nombre":"Mixto","precioExtra":0,"porDefecto":false}]},{"id":"salsas","titulo":"Salsas","tipo":"multiple","textoSiVacio":"Sin salsa","opciones":[{"id":"salsa-blanca","nombre":"Salsa de yogurt (Blanca)","ingrediente":"salsa blanca","precioExtra":0,"porDefecto":true},{"id":"salsa-roja","nombre":"Salsa de tomate (Roja)","ingrediente":"salsa roja","precioExtra":0,"porDefecto":true},{"id":"salsa-picante","nombre":"Salsa picante","ingrediente":"salsa picante","precioExtra":0,"porDefecto":false}]},{"id":"extras","titulo":"Extras","tipo":"multiple","opciones":[{"id":"extra-salsa","nombre":"Extra salsa","precioExtra":1,"porDefecto":false},{"id":"extra-queso","nombre":"Extra queso","precioExtra":1,"porDefecto":false},{"id":"pan-kebab","nombre":"Pan de kebab","precioExtra":1,"porDefecto":false}]}]'::jsonb where id = 'pedratas-mediana';
update menu_productos set precio = 7, modificadores = '[{"id":"carne","titulo":"Elige la carne","tipo":"unica","maxSeleccion":1,"opciones":[{"id":"ternera","nombre":"Ternera","precioExtra":0,"porDefecto":true},{"id":"pollo","nombre":"Pollo","precioExtra":0,"porDefecto":false},{"id":"mixto","nombre":"Mixto","precioExtra":0,"porDefecto":false}]},{"id":"salsas","titulo":"Salsas","tipo":"multiple","textoSiVacio":"Sin salsa","opciones":[{"id":"salsa-blanca","nombre":"Salsa de yogurt (Blanca)","ingrediente":"salsa blanca","precioExtra":0,"porDefecto":true},{"id":"salsa-roja","nombre":"Salsa de tomate (Roja)","ingrediente":"salsa roja","precioExtra":0,"porDefecto":true},{"id":"salsa-picante","nombre":"Salsa picante","ingrediente":"salsa picante","precioExtra":0,"porDefecto":false}]},{"id":"extras","titulo":"Extras","tipo":"multiple","opciones":[{"id":"extra-salsa","nombre":"Extra salsa","precioExtra":1,"porDefecto":false},{"id":"extra-queso","nombre":"Extra queso","precioExtra":1,"porDefecto":false},{"id":"pan-kebab","nombre":"Pan de kebab","precioExtra":1,"porDefecto":false}]}]'::jsonb where id = 'pedratas-grande';

insert into menu_productos (id, categoria_id, nombre, descripcion, precio, modificadores, orden)
select 'pedratas-xxl', id, 'Pedrata XXL', 'Patatas, carne y salsa', 12, '[{"id":"carne","titulo":"Elige la carne","tipo":"unica","maxSeleccion":1,"opciones":[{"id":"ternera","nombre":"Ternera","precioExtra":0,"porDefecto":true},{"id":"pollo","nombre":"Pollo","precioExtra":0,"porDefecto":false},{"id":"mixto","nombre":"Mixto","precioExtra":0,"porDefecto":false}]},{"id":"salsas","titulo":"Salsas","tipo":"multiple","textoSiVacio":"Sin salsa","opciones":[{"id":"salsa-blanca","nombre":"Salsa de yogurt (Blanca)","ingrediente":"salsa blanca","precioExtra":0,"porDefecto":true},{"id":"salsa-roja","nombre":"Salsa de tomate (Roja)","ingrediente":"salsa roja","precioExtra":0,"porDefecto":true},{"id":"salsa-picante","nombre":"Salsa picante","ingrediente":"salsa picante","precioExtra":0,"porDefecto":false}]},{"id":"extras","titulo":"Extras","tipo":"multiple","opciones":[{"id":"extra-salsa","nombre":"Extra salsa","precioExtra":1,"porDefecto":false},{"id":"extra-queso","nombre":"Extra queso","precioExtra":1,"porDefecto":false},{"id":"pan-kebab","nombre":"Pan de kebab","precioExtra":1,"porDefecto":false}]}]'::jsonb, 3
from menu_categorias where nombre = 'Pedratas'
on conflict (id) do update set
  categoria_id = excluded.categoria_id,
  nombre = excluded.nombre,
  descripcion = excluded.descripcion,
  precio = excluded.precio,
  modificadores = excluded.modificadores,
  orden = excluded.orden;
