-- Reorganización de carta: sistema de salsas en dos niveles
-- (salsas por encima, gratis / tarrinas de salsa aparte, +1€ cada una)
-- para Patatas (clásicas y deluxe, 6 productos) y para 5 de los 6
-- productos de Zona crujiente. Precios de patatas confirmados por el
-- cliente sin cambios (pequeña 4,50€, mediana 6€, grande 7€).
-- Seguro de re-ejecutar.

update menu_productos set precio = 4.5, modificadores = '[{"id":"salsas","titulo":"Salsas","tipo":"multiple","textoSiVacio":"Sin salsa","opciones":[{"id":"salsa-blanca","nombre":"Salsa de yogurt (Blanca)","ingrediente":"salsa blanca","precioExtra":0,"porDefecto":true},{"id":"salsa-roja","nombre":"Salsa de tomate (Roja)","ingrediente":"salsa roja","precioExtra":0,"porDefecto":true},{"id":"salsa-picante","nombre":"Salsa picante","ingrediente":"salsa picante","precioExtra":0,"porDefecto":false}]},{"id":"salsas-aparte","titulo":"Tarrinas de salsa aparte","tipo":"multiple","opciones":[{"id":"salsa-blanca","nombre":"Tarrina Salsa de yogurt (Blanca)","precioExtra":1,"porDefecto":false},{"id":"salsa-roja","nombre":"Tarrina Salsa de tomate (Roja)","precioExtra":1,"porDefecto":false},{"id":"salsa-picante","nombre":"Tarrina Salsa picante","precioExtra":1,"porDefecto":false}]}]'::jsonb where id = 'patatas-fritas-pequena';
update menu_productos set precio = 6, modificadores = '[{"id":"salsas","titulo":"Salsas","tipo":"multiple","textoSiVacio":"Sin salsa","opciones":[{"id":"salsa-blanca","nombre":"Salsa de yogurt (Blanca)","ingrediente":"salsa blanca","precioExtra":0,"porDefecto":true},{"id":"salsa-roja","nombre":"Salsa de tomate (Roja)","ingrediente":"salsa roja","precioExtra":0,"porDefecto":true},{"id":"salsa-picante","nombre":"Salsa picante","ingrediente":"salsa picante","precioExtra":0,"porDefecto":false}]},{"id":"salsas-aparte","titulo":"Tarrinas de salsa aparte","tipo":"multiple","opciones":[{"id":"salsa-blanca","nombre":"Tarrina Salsa de yogurt (Blanca)","precioExtra":1,"porDefecto":false},{"id":"salsa-roja","nombre":"Tarrina Salsa de tomate (Roja)","precioExtra":1,"porDefecto":false},{"id":"salsa-picante","nombre":"Tarrina Salsa picante","precioExtra":1,"porDefecto":false}]}]'::jsonb where id = 'patatas-fritas-mediana';
update menu_productos set precio = 7, modificadores = '[{"id":"salsas","titulo":"Salsas","tipo":"multiple","textoSiVacio":"Sin salsa","opciones":[{"id":"salsa-blanca","nombre":"Salsa de yogurt (Blanca)","ingrediente":"salsa blanca","precioExtra":0,"porDefecto":true},{"id":"salsa-roja","nombre":"Salsa de tomate (Roja)","ingrediente":"salsa roja","precioExtra":0,"porDefecto":true},{"id":"salsa-picante","nombre":"Salsa picante","ingrediente":"salsa picante","precioExtra":0,"porDefecto":false}]},{"id":"salsas-aparte","titulo":"Tarrinas de salsa aparte","tipo":"multiple","opciones":[{"id":"salsa-blanca","nombre":"Tarrina Salsa de yogurt (Blanca)","precioExtra":1,"porDefecto":false},{"id":"salsa-roja","nombre":"Tarrina Salsa de tomate (Roja)","precioExtra":1,"porDefecto":false},{"id":"salsa-picante","nombre":"Tarrina Salsa picante","precioExtra":1,"porDefecto":false}]}]'::jsonb where id = 'patatas-fritas-grande';
update menu_productos set precio = 4.5, modificadores = '[{"id":"salsas","titulo":"Salsas","tipo":"multiple","textoSiVacio":"Sin salsa","opciones":[{"id":"salsa-blanca","nombre":"Salsa de yogurt (Blanca)","ingrediente":"salsa blanca","precioExtra":0,"porDefecto":true},{"id":"salsa-roja","nombre":"Salsa de tomate (Roja)","ingrediente":"salsa roja","precioExtra":0,"porDefecto":true},{"id":"salsa-picante","nombre":"Salsa picante","ingrediente":"salsa picante","precioExtra":0,"porDefecto":false}]},{"id":"salsas-aparte","titulo":"Tarrinas de salsa aparte","tipo":"multiple","opciones":[{"id":"salsa-blanca","nombre":"Tarrina Salsa de yogurt (Blanca)","precioExtra":1,"porDefecto":false},{"id":"salsa-roja","nombre":"Tarrina Salsa de tomate (Roja)","precioExtra":1,"porDefecto":false},{"id":"salsa-picante","nombre":"Tarrina Salsa picante","precioExtra":1,"porDefecto":false}]}]'::jsonb where id = 'patatas-deluxe-pequena';
update menu_productos set precio = 6, modificadores = '[{"id":"salsas","titulo":"Salsas","tipo":"multiple","textoSiVacio":"Sin salsa","opciones":[{"id":"salsa-blanca","nombre":"Salsa de yogurt (Blanca)","ingrediente":"salsa blanca","precioExtra":0,"porDefecto":true},{"id":"salsa-roja","nombre":"Salsa de tomate (Roja)","ingrediente":"salsa roja","precioExtra":0,"porDefecto":true},{"id":"salsa-picante","nombre":"Salsa picante","ingrediente":"salsa picante","precioExtra":0,"porDefecto":false}]},{"id":"salsas-aparte","titulo":"Tarrinas de salsa aparte","tipo":"multiple","opciones":[{"id":"salsa-blanca","nombre":"Tarrina Salsa de yogurt (Blanca)","precioExtra":1,"porDefecto":false},{"id":"salsa-roja","nombre":"Tarrina Salsa de tomate (Roja)","precioExtra":1,"porDefecto":false},{"id":"salsa-picante","nombre":"Tarrina Salsa picante","precioExtra":1,"porDefecto":false}]}]'::jsonb where id = 'patatas-deluxe-mediana';
update menu_productos set precio = 7, modificadores = '[{"id":"salsas","titulo":"Salsas","tipo":"multiple","textoSiVacio":"Sin salsa","opciones":[{"id":"salsa-blanca","nombre":"Salsa de yogurt (Blanca)","ingrediente":"salsa blanca","precioExtra":0,"porDefecto":true},{"id":"salsa-roja","nombre":"Salsa de tomate (Roja)","ingrediente":"salsa roja","precioExtra":0,"porDefecto":true},{"id":"salsa-picante","nombre":"Salsa picante","ingrediente":"salsa picante","precioExtra":0,"porDefecto":false}]},{"id":"salsas-aparte","titulo":"Tarrinas de salsa aparte","tipo":"multiple","opciones":[{"id":"salsa-blanca","nombre":"Tarrina Salsa de yogurt (Blanca)","precioExtra":1,"porDefecto":false},{"id":"salsa-roja","nombre":"Tarrina Salsa de tomate (Roja)","precioExtra":1,"porDefecto":false},{"id":"salsa-picante","nombre":"Tarrina Salsa picante","precioExtra":1,"porDefecto":false}]}]'::jsonb where id = 'patatas-deluxe-grande';

-- Zona crujiente: alitas, nuggets, palomitas, tiras y la tarrina de arroz
-- basmati con falafel llevan solo el sistema de salsas (igual que
-- patatas). El burrito, además, lleva su propio paso de quitar
-- ingredientes y su propio paso de extras (ver más abajo).
update menu_productos set modificadores = '[{"id":"salsas","titulo":"Salsas","tipo":"multiple","textoSiVacio":"Sin salsa","opciones":[{"id":"salsa-blanca","nombre":"Salsa de yogurt (Blanca)","ingrediente":"salsa blanca","precioExtra":0,"porDefecto":true},{"id":"salsa-roja","nombre":"Salsa de tomate (Roja)","ingrediente":"salsa roja","precioExtra":0,"porDefecto":true},{"id":"salsa-picante","nombre":"Salsa picante","ingrediente":"salsa picante","precioExtra":0,"porDefecto":false}]},{"id":"salsas-aparte","titulo":"Tarrinas de salsa aparte","tipo":"multiple","opciones":[{"id":"salsa-blanca","nombre":"Tarrina Salsa de yogurt (Blanca)","precioExtra":1,"porDefecto":false},{"id":"salsa-roja","nombre":"Tarrina Salsa de tomate (Roja)","precioExtra":1,"porDefecto":false},{"id":"salsa-picante","nombre":"Tarrina Salsa picante","precioExtra":1,"porDefecto":false}]}]'::jsonb where id = 'alitas-pollo';
update menu_productos set modificadores = '[{"id":"salsas","titulo":"Salsas","tipo":"multiple","textoSiVacio":"Sin salsa","opciones":[{"id":"salsa-blanca","nombre":"Salsa de yogurt (Blanca)","ingrediente":"salsa blanca","precioExtra":0,"porDefecto":true},{"id":"salsa-roja","nombre":"Salsa de tomate (Roja)","ingrediente":"salsa roja","precioExtra":0,"porDefecto":true},{"id":"salsa-picante","nombre":"Salsa picante","ingrediente":"salsa picante","precioExtra":0,"porDefecto":false}]},{"id":"salsas-aparte","titulo":"Tarrinas de salsa aparte","tipo":"multiple","opciones":[{"id":"salsa-blanca","nombre":"Tarrina Salsa de yogurt (Blanca)","precioExtra":1,"porDefecto":false},{"id":"salsa-roja","nombre":"Tarrina Salsa de tomate (Roja)","precioExtra":1,"porDefecto":false},{"id":"salsa-picante","nombre":"Tarrina Salsa picante","precioExtra":1,"porDefecto":false}]}]'::jsonb where id = 'nuggets-pollo';
update menu_productos set modificadores = '[{"id":"salsas","titulo":"Salsas","tipo":"multiple","textoSiVacio":"Sin salsa","opciones":[{"id":"salsa-blanca","nombre":"Salsa de yogurt (Blanca)","ingrediente":"salsa blanca","precioExtra":0,"porDefecto":true},{"id":"salsa-roja","nombre":"Salsa de tomate (Roja)","ingrediente":"salsa roja","precioExtra":0,"porDefecto":true},{"id":"salsa-picante","nombre":"Salsa picante","ingrediente":"salsa picante","precioExtra":0,"porDefecto":false}]},{"id":"salsas-aparte","titulo":"Tarrinas de salsa aparte","tipo":"multiple","opciones":[{"id":"salsa-blanca","nombre":"Tarrina Salsa de yogurt (Blanca)","precioExtra":1,"porDefecto":false},{"id":"salsa-roja","nombre":"Tarrina Salsa de tomate (Roja)","precioExtra":1,"porDefecto":false},{"id":"salsa-picante","nombre":"Tarrina Salsa picante","precioExtra":1,"porDefecto":false}]}]'::jsonb where id = 'palomitas-pollo';
update menu_productos set modificadores = '[{"id":"salsas","titulo":"Salsas","tipo":"multiple","textoSiVacio":"Sin salsa","opciones":[{"id":"salsa-blanca","nombre":"Salsa de yogurt (Blanca)","ingrediente":"salsa blanca","precioExtra":0,"porDefecto":true},{"id":"salsa-roja","nombre":"Salsa de tomate (Roja)","ingrediente":"salsa roja","precioExtra":0,"porDefecto":true},{"id":"salsa-picante","nombre":"Salsa picante","ingrediente":"salsa picante","precioExtra":0,"porDefecto":false}]},{"id":"salsas-aparte","titulo":"Tarrinas de salsa aparte","tipo":"multiple","opciones":[{"id":"salsa-blanca","nombre":"Tarrina Salsa de yogurt (Blanca)","precioExtra":1,"porDefecto":false},{"id":"salsa-roja","nombre":"Tarrina Salsa de tomate (Roja)","precioExtra":1,"porDefecto":false},{"id":"salsa-picante","nombre":"Tarrina Salsa picante","precioExtra":1,"porDefecto":false}]}]'::jsonb where id = 'tiras-pollo';
update menu_productos set modificadores = '[{"id":"salsas","titulo":"Salsas","tipo":"multiple","textoSiVacio":"Sin salsa","opciones":[{"id":"salsa-blanca","nombre":"Salsa de yogurt (Blanca)","ingrediente":"salsa blanca","precioExtra":0,"porDefecto":true},{"id":"salsa-roja","nombre":"Salsa de tomate (Roja)","ingrediente":"salsa roja","precioExtra":0,"porDefecto":true},{"id":"salsa-picante","nombre":"Salsa picante","ingrediente":"salsa picante","precioExtra":0,"porDefecto":false}]},{"id":"salsas-aparte","titulo":"Tarrinas de salsa aparte","tipo":"multiple","opciones":[{"id":"salsa-blanca","nombre":"Tarrina Salsa de yogurt (Blanca)","precioExtra":1,"porDefecto":false},{"id":"salsa-roja","nombre":"Tarrina Salsa de tomate (Roja)","precioExtra":1,"porDefecto":false},{"id":"salsa-picante","nombre":"Tarrina Salsa picante","precioExtra":1,"porDefecto":false}]}]'::jsonb where id = 'tarrina-arroz-falafel';

update menu_productos set modificadores = '[{"id":"quitar","titulo":"Quitar ingredientes","tipo":"multiple","opciones":[{"id":"sin-tomate","nombre":"Sin tomate","ingrediente":"tomate","precioExtra":0,"porDefecto":false},{"id":"sin-cebolla","nombre":"Sin cebolla","ingrediente":"cebolla","precioExtra":0,"porDefecto":false},{"id":"sin-repollo-zanahoria","nombre":"Sin repollo y zanahoria","ingrediente":"repollo y zanahoria","precioExtra":0,"porDefecto":false},{"id":"sin-lechuga","nombre":"Sin lechuga","ingrediente":"lechuga","precioExtra":0,"porDefecto":false},{"id":"sin-patatas","nombre":"Sin patatas","ingrediente":"patatas","precioExtra":0,"porDefecto":false}]},{"id":"salsas","titulo":"Salsas","tipo":"multiple","textoSiVacio":"Sin salsa","opciones":[{"id":"salsa-blanca","nombre":"Salsa de yogurt (Blanca)","ingrediente":"salsa blanca","precioExtra":0,"porDefecto":true},{"id":"salsa-roja","nombre":"Salsa de tomate (Roja)","ingrediente":"salsa roja","precioExtra":0,"porDefecto":true},{"id":"salsa-picante","nombre":"Salsa picante","ingrediente":"salsa picante","precioExtra":0,"porDefecto":false}]},{"id":"salsas-aparte","titulo":"Tarrinas de salsa aparte","tipo":"multiple","opciones":[{"id":"salsa-blanca","nombre":"Tarrina Salsa de yogurt (Blanca)","precioExtra":1,"porDefecto":false},{"id":"salsa-roja","nombre":"Tarrina Salsa de tomate (Roja)","precioExtra":1,"porDefecto":false},{"id":"salsa-picante","nombre":"Tarrina Salsa picante","precioExtra":1,"porDefecto":false}]},{"id":"extras","titulo":"Extras","tipo":"multiple","opciones":[{"id":"extra-salsa","nombre":"Extra salsa","precioExtra":1,"porDefecto":false},{"id":"extra-queso","nombre":"Extra queso","precioExtra":1,"porDefecto":false},{"id":"extra-pollo-crujiente","nombre":"Extra pollo crujiente","precioExtra":1.5,"porDefecto":false}]}]'::jsonb where id = 'burrito';

-- Complementos: solo el falafel lleva paso de salsas — aros de cebolla,
-- samosa, cheese bites y pan de kebab van sin modificadores.
update menu_productos set modificadores = '[{"id":"salsas","titulo":"Salsas","tipo":"multiple","textoSiVacio":"Sin salsa","opciones":[{"id":"salsa-blanca","nombre":"Salsa de yogurt (Blanca)","ingrediente":"salsa blanca","precioExtra":0,"porDefecto":true},{"id":"salsa-roja","nombre":"Salsa de tomate (Roja)","ingrediente":"salsa roja","precioExtra":0,"porDefecto":true},{"id":"salsa-picante","nombre":"Salsa picante","ingrediente":"salsa picante","precioExtra":0,"porDefecto":false}]}]'::jsonb where id = 'falafel-porcion';
update menu_productos set modificadores = null where id = 'aros-cebolla';
update menu_productos set modificadores = null where id = 'samosa';
update menu_productos set modificadores = null where id = 'cheese-bites';
update menu_productos set modificadores = null where id = 'pan-kebab';
