-- Reorganización de carta: "Pizza a tu gusto" gana un paso de
-- ingredientes (13 opciones). Salsa de tomate y queso van siempre
-- incluidos en la base (no cuentan en este paso). De los ingredientes que
-- elija el cliente, los 3 primeros son gratis y cada uno de más cuesta
-- +1€ — "primeros" se decide por precio, no por orden de selección (ver
-- primerosGratis en client/api/orders/index.js).
-- Seguro de re-ejecutar.

update menu_productos set modificadores = '[{"id":"ingredientes","titulo":"Elige tus ingredientes (3 primeros gratis, +1€ el resto)","tipo":"multiple","primerosGratis":3,"opciones":[{"id":"ternera","nombre":"Ternera","precioExtra":1,"porDefecto":false},{"id":"pollo","nombre":"Pollo","precioExtra":1,"porDefecto":false},{"id":"aceitunas-negras","nombre":"Aceitunas negras","precioExtra":1,"porDefecto":false},{"id":"champinones","nombre":"Champiñones","precioExtra":1,"porDefecto":false},{"id":"maiz","nombre":"Maíz","precioExtra":1,"porDefecto":false},{"id":"tomate-natural","nombre":"Tomate natural","precioExtra":1,"porDefecto":false},{"id":"bacon","nombre":"Bacon","precioExtra":1,"porDefecto":false},{"id":"jamon","nombre":"Jamón","precioExtra":1,"porDefecto":false},{"id":"chorizo","nombre":"Chorizo","precioExtra":1,"porDefecto":false},{"id":"cebolla","nombre":"Cebolla","precioExtra":1,"porDefecto":false},{"id":"jalapenos","nombre":"Jalapeños","precioExtra":1,"porDefecto":false},{"id":"pimientos","nombre":"Pimientos","precioExtra":1,"porDefecto":false},{"id":"atun","nombre":"Atún","precioExtra":1,"porDefecto":false}]}]'::jsonb where id = 'pizza-a-tu-gusto-pequena';
update menu_productos set modificadores = '[{"id":"ingredientes","titulo":"Elige tus ingredientes (3 primeros gratis, +1€ el resto)","tipo":"multiple","primerosGratis":3,"opciones":[{"id":"ternera","nombre":"Ternera","precioExtra":1,"porDefecto":false},{"id":"pollo","nombre":"Pollo","precioExtra":1,"porDefecto":false},{"id":"aceitunas-negras","nombre":"Aceitunas negras","precioExtra":1,"porDefecto":false},{"id":"champinones","nombre":"Champiñones","precioExtra":1,"porDefecto":false},{"id":"maiz","nombre":"Maíz","precioExtra":1,"porDefecto":false},{"id":"tomate-natural","nombre":"Tomate natural","precioExtra":1,"porDefecto":false},{"id":"bacon","nombre":"Bacon","precioExtra":1,"porDefecto":false},{"id":"jamon","nombre":"Jamón","precioExtra":1,"porDefecto":false},{"id":"chorizo","nombre":"Chorizo","precioExtra":1,"porDefecto":false},{"id":"cebolla","nombre":"Cebolla","precioExtra":1,"porDefecto":false},{"id":"jalapenos","nombre":"Jalapeños","precioExtra":1,"porDefecto":false},{"id":"pimientos","nombre":"Pimientos","precioExtra":1,"porDefecto":false},{"id":"atun","nombre":"Atún","precioExtra":1,"porDefecto":false}]}]'::jsonb where id = 'pizza-a-tu-gusto-mediana';
update menu_productos set modificadores = '[{"id":"ingredientes","titulo":"Elige tus ingredientes (3 primeros gratis, +1€ el resto)","tipo":"multiple","primerosGratis":3,"opciones":[{"id":"ternera","nombre":"Ternera","precioExtra":1,"porDefecto":false},{"id":"pollo","nombre":"Pollo","precioExtra":1,"porDefecto":false},{"id":"aceitunas-negras","nombre":"Aceitunas negras","precioExtra":1,"porDefecto":false},{"id":"champinones","nombre":"Champiñones","precioExtra":1,"porDefecto":false},{"id":"maiz","nombre":"Maíz","precioExtra":1,"porDefecto":false},{"id":"tomate-natural","nombre":"Tomate natural","precioExtra":1,"porDefecto":false},{"id":"bacon","nombre":"Bacon","precioExtra":1,"porDefecto":false},{"id":"jamon","nombre":"Jamón","precioExtra":1,"porDefecto":false},{"id":"chorizo","nombre":"Chorizo","precioExtra":1,"porDefecto":false},{"id":"cebolla","nombre":"Cebolla","precioExtra":1,"porDefecto":false},{"id":"jalapenos","nombre":"Jalapeños","precioExtra":1,"porDefecto":false},{"id":"pimientos","nombre":"Pimientos","precioExtra":1,"porDefecto":false},{"id":"atun","nombre":"Atún","precioExtra":1,"porDefecto":false}]}]'::jsonb where id = 'pizza-a-tu-gusto-familiar';
