-- Reorganización de carta: Hamburguesas (categoría nueva, 3
-- productos), Perrito caliente (categoría nueva), Pollo asado (categoría
-- nueva) y Ensaladas (paso de quitar ingredientes propio por ensalada).
-- Seguro de re-ejecutar.

-- Hamburguesas — se renombra "Hamburguesa" a "Hamburguesa de vacuno" para
-- que quede claro frente a la de pollo crispy (mismo precio, 4,50€).
update menu_productos set nombre = 'Hamburguesa de vacuno', modificadores = '[{"id":"quitar","titulo":"Quitar ingredientes","tipo":"multiple","opciones":[{"id":"sin-queso","nombre":"Sin queso","ingrediente":"queso","precioExtra":0,"porDefecto":false},{"id":"sin-lechuga","nombre":"Sin lechuga","ingrediente":"lechuga","precioExtra":0,"porDefecto":false},{"id":"sin-tomate","nombre":"Sin tomate","ingrediente":"tomate","precioExtra":0,"porDefecto":false},{"id":"sin-cebolla","nombre":"Sin cebolla","ingrediente":"cebolla","precioExtra":0,"porDefecto":false},{"id":"sin-ketchup","nombre":"Sin ketchup","ingrediente":"ketchup","precioExtra":0,"porDefecto":false},{"id":"sin-mayonesa","nombre":"Sin mayonesa","ingrediente":"mayonesa","precioExtra":0,"porDefecto":false}]},{"id":"extras","titulo":"Extras","tipo":"multiple","opciones":[{"id":"extra-huevo","nombre":"Extra huevo","precioExtra":1,"porDefecto":false},{"id":"extra-bacon","nombre":"Extra bacon","precioExtra":1,"porDefecto":false}]}]'::jsonb where id = 'hamburguesa-clasica';
update menu_productos set modificadores = '[{"id":"quitar","titulo":"Quitar ingredientes","tipo":"multiple","opciones":[{"id":"sin-queso","nombre":"Sin queso","ingrediente":"queso","precioExtra":0,"porDefecto":false},{"id":"sin-lechuga","nombre":"Sin lechuga","ingrediente":"lechuga","precioExtra":0,"porDefecto":false},{"id":"sin-tomate","nombre":"Sin tomate","ingrediente":"tomate","precioExtra":0,"porDefecto":false},{"id":"sin-cebolla","nombre":"Sin cebolla","ingrediente":"cebolla","precioExtra":0,"porDefecto":false},{"id":"sin-ketchup","nombre":"Sin ketchup","ingrediente":"ketchup","precioExtra":0,"porDefecto":false},{"id":"sin-mayonesa","nombre":"Sin mayonesa","ingrediente":"mayonesa","precioExtra":0,"porDefecto":false}]},{"id":"extras","titulo":"Extras","tipo":"multiple","opciones":[{"id":"extra-huevo","nombre":"Extra huevo","precioExtra":1,"porDefecto":false},{"id":"extra-bacon","nombre":"Extra bacon","precioExtra":1,"porDefecto":false}]}]'::jsonb where id = 'hamburguesa-pollo-crispy';
update menu_productos set modificadores = '[{"id":"quitar","titulo":"Quitar ingredientes","tipo":"multiple","opciones":[{"id":"sin-queso","nombre":"Sin queso","ingrediente":"queso","precioExtra":0,"porDefecto":false},{"id":"sin-lechuga","nombre":"Sin lechuga","ingrediente":"lechuga","precioExtra":0,"porDefecto":false},{"id":"sin-tomate","nombre":"Sin tomate","ingrediente":"tomate","precioExtra":0,"porDefecto":false},{"id":"sin-cebolla","nombre":"Sin cebolla","ingrediente":"cebolla","precioExtra":0,"porDefecto":false},{"id":"sin-huevo","nombre":"Sin huevo","ingrediente":"huevo","precioExtra":0,"porDefecto":false},{"id":"sin-bacon","nombre":"Sin bacon","ingrediente":"bacon","precioExtra":0,"porDefecto":false},{"id":"sin-ketchup","nombre":"Sin ketchup","ingrediente":"ketchup","precioExtra":0,"porDefecto":false},{"id":"sin-mayonesa","nombre":"Sin mayonesa","ingrediente":"mayonesa","precioExtra":0,"porDefecto":false}]},{"id":"extras","titulo":"Extras","tipo":"multiple","opciones":[{"id":"extra-huevo","nombre":"Extra huevo","precioExtra":1,"porDefecto":false},{"id":"extra-bacon","nombre":"Extra bacon","precioExtra":1,"porDefecto":false}]}]'::jsonb where id = 'hamburguesa-xxl';

-- Perrito caliente
update menu_productos set modificadores = '[{"id":"quitar","titulo":"Quitar ingredientes","tipo":"multiple","opciones":[{"id":"sin-salchicha","nombre":"Sin salchicha","ingrediente":"salchicha","precioExtra":0,"porDefecto":false},{"id":"sin-ketchup","nombre":"Sin ketchup","ingrediente":"ketchup","precioExtra":0,"porDefecto":false},{"id":"sin-mayonesa","nombre":"Sin mayonesa","ingrediente":"mayonesa","precioExtra":0,"porDefecto":false}]}]'::jsonb where id = 'perrito-caliente';

-- Pollo asado
update menu_productos set modificadores = '[{"id":"quitar","titulo":"Quitar ingredientes","tipo":"multiple","opciones":[{"id":"sin-patatas","nombre":"Sin patatas","ingrediente":"patatas","precioExtra":0,"porDefecto":false},{"id":"sin-salsa-pollo","nombre":"Sin salsa del pollo","ingrediente":"salsa del pollo","precioExtra":0,"porDefecto":false}]},{"id":"extras","titulo":"Extras","tipo":"multiple","opciones":[{"id":"pan-kebab","nombre":"Pan de kebab","precioExtra":1,"porDefecto":false},{"id":"salsa-blanca","nombre":"Tarrina Salsa de yogurt (Blanca)","precioExtra":1,"porDefecto":false},{"id":"salsa-roja","nombre":"Tarrina Salsa de tomate (Roja)","precioExtra":1,"porDefecto":false},{"id":"salsa-picante","nombre":"Tarrina Salsa picante","precioExtra":1,"porDefecto":false}]}]'::jsonb where id = 'pollo-asado';

-- Ensaladas: cada una con sus propios ingredientes.
update menu_productos set modificadores = '[{"id":"quitar","titulo":"Quitar ingredientes","tipo":"multiple","opciones":[{"id":"sin-lechuga","nombre":"Sin lechuga","ingrediente":"lechuga","precioExtra":0,"porDefecto":false},{"id":"sin-tomate","nombre":"Sin tomate","ingrediente":"tomate","precioExtra":0,"porDefecto":false},{"id":"sin-atun","nombre":"Sin atún","ingrediente":"atún","precioExtra":0,"porDefecto":false},{"id":"sin-cebolla","nombre":"Sin cebolla","ingrediente":"cebolla","precioExtra":0,"porDefecto":false},{"id":"sin-repollo","nombre":"Sin repollo","ingrediente":"repollo","precioExtra":0,"porDefecto":false},{"id":"sin-zanahoria","nombre":"Sin zanahoria","ingrediente":"zanahoria","precioExtra":0,"porDefecto":false},{"id":"sin-maiz","nombre":"Sin maíz","ingrediente":"maíz","precioExtra":0,"porDefecto":false}]}]'::jsonb where id = 'ensalada-merindades';

update menu_productos set modificadores = '[{"id":"quitar","titulo":"Quitar ingredientes","tipo":"multiple","opciones":[{"id":"sin-lechuga","nombre":"Sin lechuga","ingrediente":"lechuga","precioExtra":0,"porDefecto":false},{"id":"sin-maiz","nombre":"Sin maíz","ingrediente":"maíz","precioExtra":0,"porDefecto":false},{"id":"sin-zanahoria","nombre":"Sin zanahoria","ingrediente":"zanahoria","precioExtra":0,"porDefecto":false},{"id":"sin-aceitunas","nombre":"Sin aceitunas","ingrediente":"aceitunas","precioExtra":0,"porDefecto":false},{"id":"sin-repollo","nombre":"Sin repollo","ingrediente":"repollo","precioExtra":0,"porDefecto":false},{"id":"sin-salsa-yogur","nombre":"Sin salsa de yogur","ingrediente":"salsa de yogur","precioExtra":0,"porDefecto":false}]}]'::jsonb where id = 'ensalada-california';

update menu_productos set modificadores = '[{"id":"quitar","titulo":"Quitar ingredientes","tipo":"multiple","opciones":[{"id":"sin-pollo-crujiente","nombre":"Sin pollo crujiente","ingrediente":"pollo crujiente","precioExtra":0,"porDefecto":false},{"id":"sin-lechuga","nombre":"Sin lechuga","ingrediente":"lechuga","precioExtra":0,"porDefecto":false},{"id":"sin-tomate","nombre":"Sin tomate","ingrediente":"tomate","precioExtra":0,"porDefecto":false},{"id":"sin-cebolla","nombre":"Sin cebolla","ingrediente":"cebolla","precioExtra":0,"porDefecto":false},{"id":"sin-aceituna","nombre":"Sin aceituna","ingrediente":"aceituna","precioExtra":0,"porDefecto":false},{"id":"sin-maiz","nombre":"Sin maíz","ingrediente":"maíz","precioExtra":0,"porDefecto":false}]}]'::jsonb where id = 'ensalada-cocktail';
