-- Traducciones al inglés del menú existente (categorías + productos).
-- Generado a partir del contenido en español de supabase/migration.sql.
-- Seguro de re-ejecutar: solo actualiza nombre_en/descripcion_en de filas ya existentes.

-- Categorías
update menu_categorias set nombre_en = 'Kebab' where nombre = 'Kebab';
update menu_categorias set nombre_en = 'Dürüm' where nombre = 'Dürüm';
update menu_categorias set nombre_en = 'Lahmacum' where nombre = 'Lahmacum';
update menu_categorias set nombre_en = 'Combo Plates' where nombre = 'Platos combinados';
update menu_categorias set nombre_en = 'Specialties' where nombre = 'Especialidades';
update menu_categorias set nombre_en = 'Fries & Snacks' where nombre = 'Patatas y snacks';
update menu_categorias set nombre_en = 'Sauces' where nombre = 'Salsas';
update menu_categorias set nombre_en = 'Drinks' where nombre = 'Bebidas';
update menu_categorias set nombre_en = 'Salads' where nombre = 'Ensaladas';
update menu_categorias set nombre_en = 'Pizzas' where nombre = 'Pizzas';
update menu_categorias set nombre_en = 'Make It a Meal' where nombre = 'Haz tu menú';

-- Productos
update menu_productos set nombre_en = 'Beef kebab', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces' where id = 'kebab-ternera';
update menu_productos set nombre_en = 'Chicken kebab', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces' where id = 'kebab-pollo';
update menu_productos set nombre_en = 'Mixed kebab', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces' where id = 'kebab-mixto';
update menu_productos set nombre_en = 'Falafel kebab', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces' where id = 'kebab-falafel';
update menu_productos set nombre_en = 'Veggie kebab with gouda cheese', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces' where id = 'kebab-vegetal-queso';
update menu_productos set nombre_en = 'Meat-only kebab', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces' where id = 'kebab-solo-carne';
update menu_productos set nombre_en = 'Loaded kebab (with fries inside)', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces' where id = 'kebab-loco';
update menu_productos set nombre_en = 'Double kebab', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces' where id = 'kebab-doble';
update menu_productos set nombre_en = 'Beef dürüm', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces' where id = 'durum-ternera';
update menu_productos set nombre_en = 'Chicken dürüm', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces' where id = 'durum-pollo';
update menu_productos set nombre_en = 'Mixed dürüm', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces' where id = 'durum-mixto';
update menu_productos set nombre_en = 'Falafel dürüm', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces' where id = 'durum-falafel';
update menu_productos set nombre_en = 'Veggie dürüm with gouda cheese', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces' where id = 'durum-vegetal-queso';
update menu_productos set nombre_en = 'Meat-only dürüm', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces' where id = 'durum-solo-carne';
update menu_productos set nombre_en = 'Loaded dürüm (with fries inside)', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces' where id = 'durum-loco';
update menu_productos set nombre_en = 'Double dürüm', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces' where id = 'durum-doble';
update menu_productos set nombre_en = 'Beef lahmacum', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces' where id = 'lahmacum-ternera';
update menu_productos set nombre_en = 'Chicken lahmacum', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces' where id = 'lahmacum-pollo';
update menu_productos set nombre_en = 'Mixed lahmacum', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces' where id = 'lahmacum-mixto';
update menu_productos set nombre_en = 'Falafel lahmacum', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces' where id = 'lahmacum-falafel';
update menu_productos set nombre_en = 'Veggie lahmacum with gouda cheese', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces' where id = 'lahmacum-vegetal-queso';
update menu_productos set nombre_en = 'Meat-only lahmacum', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces' where id = 'lahmacum-solo-carne';
update menu_productos set nombre_en = 'Loaded lahmacum (with fries inside)', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces' where id = 'lahmacum-loco';
update menu_productos set nombre_en = 'Double lahmacum', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces' where id = 'lahmacum-doble';
update menu_productos set nombre_en = 'Beef platter', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces, fries and bread' where id = 'plato-ternera';
update menu_productos set nombre_en = 'Chicken platter', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces, fries and bread' where id = 'plato-pollo';
update menu_productos set nombre_en = 'Mixed platter', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces, fries and bread' where id = 'plato-mixto';
update menu_productos set nombre_en = 'Falafel platter', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces, fries and bread' where id = 'plato-falafel';
update menu_productos set nombre_en = 'Meat platter with cheese', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces, fries and bread' where id = 'plato-carne-queso';
update menu_productos set nombre_en = 'Meat-only platter', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces, fries and bread' where id = 'plato-solo-carne';
update menu_productos set nombre_en = 'Meat-only platter with cheese', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces, fries and bread' where id = 'plato-solo-carne-queso';
update menu_productos set nombre_en = 'Rice platter with meat', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces, fries and bread' where id = 'plato-arroz-carne';
update menu_productos set nombre_en = 'Double platter', descripcion_en = 'Lettuce, tomato, onion, cabbage and carrot + sauces, fries and bread' where id = 'plato-doble';
update menu_productos set nombre_en = 'Roast chicken', descripcion_en = 'With fries' where id = 'pollo-asado';
update menu_productos set nombre_en = 'Chicken wings (6 pcs)', descripcion_en = 'With fries' where id = 'alitas-pollo';
update menu_productos set nombre_en = 'Chicken nuggets (8 pcs)', descripcion_en = 'With fries' where id = 'nuggets-pollo';
update menu_productos set nombre_en = 'Chicken popcorn (15 pcs)', descripcion_en = 'With fries' where id = 'palomitas-pollo';
update menu_productos set nombre_en = 'Crispy chicken strips (4 pcs)', descripcion_en = 'With fries' where id = 'tiras-pollo';
update menu_productos set nombre_en = 'Crispy chicken burger', descripcion_en = 'Crispy chicken, lettuce, tomato, cheese, onion, ketchup and mayo' where id = 'hamburguesa-pollo-crispy';
update menu_productos set nombre_en = 'Burger', descripcion_en = 'Beef, lettuce, tomato, cheese, onion, ketchup and mayo. +egg or bacon +€1' where id = 'hamburguesa-clasica';
update menu_productos set nombre_en = 'XXL burger', descripcion_en = 'Double beef, fried egg, crispy bacon and double cheese' where id = 'hamburguesa-xxl';
update menu_productos set nombre_en = 'Pedratas (small)', descripcion_en = 'Fries, beef or chicken and sauce' where id = 'pedratas-pequena';
update menu_productos set nombre_en = 'Pedratas (medium)', descripcion_en = 'Fries, beef or chicken and sauce' where id = 'pedratas-mediana';
update menu_productos set nombre_en = 'Pedratas (large)', descripcion_en = 'Fries, beef or chicken and sauce' where id = 'pedratas-grande';
update menu_productos set nombre_en = 'Fries (small)', descripcion_en = '' where id = 'patatas-fritas-pequena';
update menu_productos set nombre_en = 'Fries (medium)', descripcion_en = '' where id = 'patatas-fritas-mediana';
update menu_productos set nombre_en = 'Fries (large)', descripcion_en = '' where id = 'patatas-fritas-grande';
update menu_productos set nombre_en = 'Deluxe wedge fries (small)', descripcion_en = '' where id = 'patatas-deluxe-pequena';
update menu_productos set nombre_en = 'Deluxe wedge fries (medium)', descripcion_en = '' where id = 'patatas-deluxe-mediana';
update menu_productos set nombre_en = 'Deluxe wedge fries (large)', descripcion_en = '' where id = 'patatas-deluxe-grande';
update menu_productos set nombre_en = 'Burrito (chicken wrap)', descripcion_en = 'Salad, crispy chicken, fries and sauce' where id = 'burrito';
update menu_productos set nombre_en = 'Hot dog', descripcion_en = 'Hot dog, ketchup and mayo' where id = 'perrito-caliente';
update menu_productos set nombre_en = 'Onion rings (8 pcs)', descripcion_en = '' where id = 'aros-cebolla';
update menu_productos set nombre_en = 'Samosas (3 pcs)', descripcion_en = '' where id = 'samosa';
update menu_productos set nombre_en = 'Cheese bites (10 pcs)', descripcion_en = '' where id = 'cheese-bites';
update menu_productos set nombre_en = 'Basmati rice bowl with falafel', descripcion_en = '' where id = 'tarrina-arroz-falafel';
update menu_productos set nombre_en = 'Falafel (6 pcs)', descripcion_en = '' where id = 'falafel-porcion';
update menu_productos set nombre_en = 'Kebab bread', descripcion_en = '' where id = 'pan-kebab';
update menu_productos set nombre_en = 'White sauce', descripcion_en = '' where id = 'salsa-blanca';
update menu_productos set nombre_en = 'Red sauce', descripcion_en = '' where id = 'salsa-roja';
update menu_productos set nombre_en = 'Spicy sauce', descripcion_en = '' where id = 'salsa-picante';
update menu_productos set nombre_en = 'Soft drink (33cl can)', descripcion_en = 'Coca-Cola, Fanta, Sprite...' where id = 'refresco-lata';
update menu_productos set nombre_en = 'Water', descripcion_en = '' where id = 'agua';
update menu_productos set nombre_en = 'Energy drink', descripcion_en = '' where id = 'bebida-energetica';
update menu_productos set nombre_en = 'Ayran', descripcion_en = 'Turkish yogurt drink' where id = 'ayran';
update menu_productos set nombre_en = 'Merindades Salad', descripcion_en = 'Lettuce, fresh tomato, tuna, onion, cabbage, carrot and corn' where id = 'ensalada-merindades';
update menu_productos set nombre_en = 'California Salad', descripcion_en = 'Lettuce, corn, carrot, olives, cabbage and a touch of yogurt dressing' where id = 'ensalada-california';
update menu_productos set nombre_en = 'Cocktail Salad', descripcion_en = 'Crispy chicken, lettuce, tomato, onion, olives and corn' where id = 'ensalada-cocktail';
update menu_productos set nombre_en = 'Doner Kebab Meal', descripcion_en = 'Fries + drink. Meat only or cheese +€1' where id = 'menu-doner-kebab';
update menu_productos set nombre_en = 'Dürüm Meal', descripcion_en = 'Fries + drink. Meat only or cheese +€1' where id = 'menu-durum';
update menu_productos set nombre_en = 'Lahmacum Meal', descripcion_en = 'Fries + drink. Meat only or cheese +€1' where id = 'menu-lahmacum';
update menu_productos set nombre_en = 'Beef/Chicken Platter Meal', descripcion_en = 'Salad + fries + drink + bread. Meat only or cheese +€1' where id = 'menu-plato-ternera-pollo';
update menu_productos set nombre_en = 'Rice Platter with Beef/Chicken Meal', descripcion_en = 'Fries + drink + sauce + bread' where id = 'menu-plato-arroz';
update menu_productos set nombre_en = 'Burger Meal (beef or crispy chicken +€1)', descripcion_en = 'Fries + drink. +egg or bacon +€1' where id = 'menu-hamburguesa';
update menu_productos set nombre_en = 'Hot Dog Meal', descripcion_en = 'Fries + drink' where id = 'menu-perrito';
update menu_productos set nombre_en = 'Chicken Wings Meal', descripcion_en = 'Salad + fries + drink' where id = 'menu-alitas';
update menu_productos set nombre_en = 'Crispy Chicken Strips Meal', descripcion_en = 'Salad + fries + drink + sauce' where id = 'menu-tiras-pollo';
update menu_productos set nombre_en = 'Burrito Meal (chicken wrap)', descripcion_en = 'Salad + fries + drink + sauce' where id = 'menu-burrito';
update menu_productos set nombre_en = 'Mixed Pizza Meal (small)', descripcion_en = 'Fries + drink' where id = 'menu-pizza-variada-pequena';
update menu_productos set nombre_en = 'Mixed Pizza Meal (medium)', descripcion_en = 'Fries + drink' where id = 'menu-pizza-variada-mediana';
update menu_productos set nombre_en = 'Four Cheese Pizza (small)', descripcion_en = 'Tomato sauce, four cheeses and oregano' where id = 'pizza-cuatro-quesos-pequena';
update menu_productos set nombre_en = 'Four Cheese Pizza (medium)', descripcion_en = 'Tomato sauce, four cheeses and oregano' where id = 'pizza-cuatro-quesos-mediana';
update menu_productos set nombre_en = 'Four Cheese Pizza (family)', descripcion_en = 'Tomato sauce, four cheeses and oregano' where id = 'pizza-cuatro-quesos-familiar';
update menu_productos set nombre_en = 'Pepperoni Pizza (small)', descripcion_en = 'Cheese, tomato sauce and pepperoni' where id = 'pizza-pepperoni-pequena';
update menu_productos set nombre_en = 'Pepperoni Pizza (medium)', descripcion_en = 'Cheese, tomato sauce and pepperoni' where id = 'pizza-pepperoni-mediana';
update menu_productos set nombre_en = 'Pepperoni Pizza (family)', descripcion_en = 'Cheese, tomato sauce and pepperoni' where id = 'pizza-pepperoni-familiar';
update menu_productos set nombre_en = 'Carbonara Pizza (small)', descripcion_en = 'Cheese, cream sauce, bacon and mushrooms' where id = 'pizza-carbonara-pequena';
update menu_productos set nombre_en = 'Carbonara Pizza (medium)', descripcion_en = 'Cheese, cream sauce, bacon and mushrooms' where id = 'pizza-carbonara-mediana';
update menu_productos set nombre_en = 'Carbonara Pizza (family)', descripcion_en = 'Cheese, cream sauce, bacon and mushrooms' where id = 'pizza-carbonara-familiar';
update menu_productos set nombre_en = 'Ibérica Pizza (small)', descripcion_en = 'Cheese, tomato sauce and ham' where id = 'pizza-iberica-pequena';
update menu_productos set nombre_en = 'Ibérica Pizza (medium)', descripcion_en = 'Cheese, tomato sauce and ham' where id = 'pizza-iberica-mediana';
update menu_productos set nombre_en = 'Ibérica Pizza (family)', descripcion_en = 'Cheese, tomato sauce and ham' where id = 'pizza-iberica-familiar';
update menu_productos set nombre_en = 'Romana Pizza (small)', descripcion_en = 'Cheese, tomato sauce, ham, chicken, olives and mushroom' where id = 'pizza-romana-pequena';
update menu_productos set nombre_en = 'Romana Pizza (medium)', descripcion_en = 'Cheese, tomato sauce, ham, chicken, olives and mushroom' where id = 'pizza-romana-mediana';
update menu_productos set nombre_en = 'Romana Pizza (family)', descripcion_en = 'Cheese, tomato sauce, ham, chicken, olives and mushroom' where id = 'pizza-romana-familiar';
update menu_productos set nombre_en = 'BBQ Pizza (small)', descripcion_en = 'Cheese, BBQ sauce, beef, pepper and oregano' where id = 'pizza-barbacoa-pequena';
update menu_productos set nombre_en = 'BBQ Pizza (medium)', descripcion_en = 'Cheese, BBQ sauce, beef, pepper and oregano' where id = 'pizza-barbacoa-mediana';
update menu_productos set nombre_en = 'BBQ Pizza (family)', descripcion_en = 'Cheese, BBQ sauce, beef, pepper and oregano' where id = 'pizza-barbacoa-familiar';
update menu_productos set nombre_en = 'Merindades Pizza (small)', descripcion_en = 'Cheese, tomato sauce, beef, chicken and oregano' where id = 'pizza-merindades-pequena';
update menu_productos set nombre_en = 'Merindades Pizza (medium)', descripcion_en = 'Cheese, tomato sauce, beef, chicken and oregano' where id = 'pizza-merindades-mediana';
update menu_productos set nombre_en = 'Merindades Pizza (family)', descripcion_en = 'Cheese, tomato sauce, beef, chicken and oregano' where id = 'pizza-merindades-familiar';
update menu_productos set nombre_en = 'Mediterranean Pizza (small)', descripcion_en = 'Cheese, tomato sauce, tuna, fresh tomato and onion' where id = 'pizza-mediterranea-pequena';
update menu_productos set nombre_en = 'Mediterranean Pizza (medium)', descripcion_en = 'Cheese, tomato sauce, tuna, fresh tomato and onion' where id = 'pizza-mediterranea-mediana';
update menu_productos set nombre_en = 'Mediterranean Pizza (family)', descripcion_en = 'Cheese, tomato sauce, tuna, fresh tomato and onion' where id = 'pizza-mediterranea-familiar';
update menu_productos set nombre_en = 'Diávola Pizza (small)', descripcion_en = 'Cheese, tomato sauce, chorizo, ham, jalapeños and a touch of spicy sauce' where id = 'pizza-diavola-pequena';
update menu_productos set nombre_en = 'Diávola Pizza (medium)', descripcion_en = 'Cheese, tomato sauce, chorizo, ham, jalapeños and a touch of spicy sauce' where id = 'pizza-diavola-mediana';
update menu_productos set nombre_en = 'Diávola Pizza (family)', descripcion_en = 'Cheese, tomato sauce, chorizo, ham, jalapeños and a touch of spicy sauce' where id = 'pizza-diavola-familiar';
update menu_productos set nombre_en = 'Toño Pizza (small)', descripcion_en = 'Cheese, tomato sauce, tuna, onion and olives' where id = 'pizza-tono-pequena';
update menu_productos set nombre_en = 'Toño Pizza (medium)', descripcion_en = 'Cheese, tomato sauce, tuna, onion and olives' where id = 'pizza-tono-mediana';
update menu_productos set nombre_en = 'Toño Pizza (family)', descripcion_en = 'Cheese, tomato sauce, tuna, onion and olives' where id = 'pizza-tono-familiar';
update menu_productos set nombre_en = 'California Pizza (small)', descripcion_en = 'Cheese, tomato sauce, beef, onion and olives' where id = 'pizza-california-pequena';
update menu_productos set nombre_en = 'California Pizza (medium)', descripcion_en = 'Cheese, tomato sauce, beef, onion and olives' where id = 'pizza-california-mediana';
update menu_productos set nombre_en = 'California Pizza (family)', descripcion_en = 'Cheese, tomato sauce, beef, onion and olives' where id = 'pizza-california-familiar';
update menu_productos set nombre_en = 'Build Your Own Pizza (small)', descripcion_en = 'Cheese, tomato and three toppings of your choice' where id = 'pizza-a-tu-gusto-pequena';
update menu_productos set nombre_en = 'Build Your Own Pizza (medium)', descripcion_en = 'Cheese, tomato and three toppings of your choice' where id = 'pizza-a-tu-gusto-mediana';
update menu_productos set nombre_en = 'Build Your Own Pizza (family)', descripcion_en = 'Cheese, tomato and three toppings of your choice' where id = 'pizza-a-tu-gusto-familiar';
update menu_productos set nombre_en = 'Vegetarian Pizza (small)', descripcion_en = 'Cheese, tomato sauce, peppers, mushrooms, onion, corn, olives, fresh tomato and oregano' where id = 'pizza-vegetariana-pequena';
update menu_productos set nombre_en = 'Vegetarian Pizza (medium)', descripcion_en = 'Cheese, tomato sauce, peppers, mushrooms, onion, corn, olives, fresh tomato and oregano' where id = 'pizza-vegetariana-mediana';
update menu_productos set nombre_en = 'Vegetarian Pizza (family)', descripcion_en = 'Cheese, tomato sauce, peppers, mushrooms, onion, corn, olives, fresh tomato and oregano' where id = 'pizza-vegetariana-familiar';
